name: CI

on:

  push:
    branches: master
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan storage.osdn.net >> ~/.ssh/known_hosts
          
      - name: Clone repo  
        run: git clone https://github.com/chunky-milk/raspbian-addons
          
      - name: Upload to OSDN
        run: rsync -avrt /home/runner/work/raspbian-addons/raspbian-addons/ hmsjy2017@storage.osdn.net:/storage/groups/r/ra/raspbian-addons
